services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - 8000
    depends_on:
      - influxdb
    networks:
      - cansat_network

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./docker/influxdb2/influxdb_data:/var/lib/influxdb2
      - ./docker/influxdb2/influxdb_config:/etc/influxdb2
    ports:
      - 8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    networks:
      - cansat_network
  
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 4000:3000
    user: "472"
    volumes:
      - ./docker/grafana/grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:8085
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - cansat_network

networks:
  cansat_network: