{
 "title": "Only IMU",
 "time": { "from": "2025-02-02T16:25:12.265Z", "to": "2025-02-03T16:25:12.265Z" },
 "panels": [
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cansat\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cansat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Accx\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "加速度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cansat\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cansat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Accx\" or r[\"_field\"] == \"Accy\" or r[\"_field\"] == \"Accz\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "角速度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cansat\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cansat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Gyrx\" or r[\"_field\"] == \"Gyry\" or r[\"_field\"] == \"Gyrz\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "地磁気",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cansat\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cansat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Magx\" or r[\"_field\"] == \"Magy\" or r[\"_field\"] == \"Magz\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "加速度",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"cansat\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cansat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Accx\" or r[\"_field\"] == \"Accy\" or r[\"_field\"] == \"Accz\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "角速度",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"cansat\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cansat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Gyrx\" or r[\"_field\"] == \"Gyry\" or r[\"_field\"] == \"Gyrz\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "地磁気",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"cansat\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cansat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Magx\" or r[\"_field\"] == \"Magy\" or r[\"_field\"] == \"Magz\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}